import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Index.module.css'
import Navbar from '@/components/navbar'


const inter = Inter({ subsets: ['latin'] })

export default function Index() {
  return (
    <>
      <Head>
        <title>First Next App</title>
        <meta property="og:title" content="My page title" key="title" />
        <meta name="description" content="Generated by create-next-app@latest" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name='author' content='DB Gautam' />
        <meta name='keywords' content='HTML, CSS, JavaScript, Next.js' />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.index}>
      <Navbar />
        <h1 className={styles.heading}>Hello World</h1> 
      </main>
    </>
  )
}
